name: bdb2024
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - numpy
  - ffmpeg
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - scipy
  - tensorflow
  - jupyter
  - pip
  - pip:
      - plottable
